eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8080
  context-path: /ImgPkService
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:8306/bosstest?useSSL=true
        username: citu_test_w
        password: citu_test_w
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    http:
        multipart:
            maxFileSize: 100Mb
            maxRequestSize: 1000Mb
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.imgpkservice.dao
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql